sudo: required
services:
  - docker

before_install:
  - docker build -t 312makce/docker-container -f Dockerfile.dev .

script:
  - docker run 312makce/docker-container npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-079441481179"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


